version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres-container-gym
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gym"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - spring-network
    volumes:
      - pgdata:/var/lib/postgresql/data     # Volume that store data from databases 
      - ./backend/sql/database:/sql                  # Directory with database structure and mock data    
  app-backend:
    build: ./backend
    container_name: spring-container-gym
    ports:
      - "8080:8080" 
    depends_on:
      - db
    networks:
      - spring-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gym
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  app-frontend:
    build: ./frontend
    ports: 
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - app-backend
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge
volumes:
  pgdata:
